-- Editor options
vim.opt.rnu = true
vim.opt.nu = true
vim.opt.paste = false
vim.opt.clipboard = "unnamedplus"
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.timeoutlen = 500
vim.opt.ignorecase = true
vim.opt.smartcase = true
vim.opt.termguicolors = true
